caktus/philly-hip

- .github/workflows/deploy.yml
- deploy/requirements.yml
- requirements/dev/dev.in
This takes advantages of new releases of django-k8s and invoke-kubesae which allow us to do deploys without leaking environment variables into the log output.
> Don't include env vars in CI output

- .github/workflows/deploy.yml
We get automatic slack notifications for tests because Github includes it in the message for each new PR. But it doesn't for deploys, so this PR uses [an integration](https://github.com/marketplace/actions/slack-github-actions-slack-integration) to notify at the end of the deploy with the status.
> Add Slack notifications for deploys

- apps/hip/templates/hip/static_page.html
Move the button inside the main column so that its click target doesn't get wiped out.
> HP-33-pt-2 Move Back button inside column

- apps/hip/models.py
- apps/hip/templates/hip/static_page.html
- apps/hip/tests.py
- apps/hip/tests/test_models.py
https://caktus.atlassian.net/browse/HP-33
Using `javascript:history.back()` doesn't work if the user has clicked on right-nav links within the page. This instead uses the `HTTP_REFERER` header to get the actual last page that the user was on, defaulting to the home page URL if it is not present (like if the user came from an email link or something)
> HP-33-try-3 get back button working

- hip/settings/base.py
https://caktus.atlassian.net/browse/HP-49
This pull request sets the project `TIME_ZONE` to 'America/New_York', so all dates and datetimes dislpay in that timezone, including in the 'Recently Updated' table.
> [HP-49] Show Datetimes US Eastern Time Zone

- apps/hip/templates/hip/home_page.html
- hip/static/styles/_colors.scss
- hip/static/styles/pages/home_page.scss
https://caktus.atlassian.net/browse/HP-44
Replacement for #29 
This uses Bulma's helpers to make the cards wrap at 4 cards per row, and changes the background color to match what is in the wireframe now.
> HP-44-vinod Wrap quicklink cards at 4 per row

- apps/hip/templates/includes/header.html
- hip/static/styles/common.scss
- hip/static/styles/includes/header.scss
- hip/static/styles/pages/base.scss
- hip/templates/base.html
This:
1. adds montserrat and open-sans using the [docs from Google](https://fonts.google.com/specimen/Open+Sans?preview.text_type=custom&sidebar.open=true&selection.family=Open+Sans:ital@1).
2. Uses montserrat for buttons and open-sans for all other text
3. Makes text of buttons uppercase
> Update fonts to match wireframes

- apps/hip/templates/hip/home_page.html
- apps/hip/templates/tags/contact_info.html
https://caktus.atlassian.net/browse/HP-47
This pull request removes the `is-vcentered` CSS class from the parent `<div>` of both the snippet column and the 'About HIP' column, so the two columns align with each other vertically.
> [HP-47] Align Snippet With Other Column

- apps/hip/templates/hip/home_page.html
- hip/static/styles/common.scss
This PR allows very long words to wrap onto next line for the `Name` column in Recently Updated table.
> HP-50 Table Zoom

- apps/hip/tests/test_utils.py
- apps/hip/utils.py
I think the existing algorithm truncates documents and pages individually before sorting, so sometimes `combined_list` will not actually receive the latest list of pages and documents.
> Fix recent updates

- apps/hip/models.py
https://caktus.atlassian.net/browse/HP-49
When a `QuickLinkCard` has a `link_page`, the `updated_date` is the `link_page`'s `latest_revision_created_at`'s date in the project timezone.
> [HP-49] Return QuickLinkCard UpdatedDate In Project Timezone

- apps/health_alerts/static/js/healthAlertPriorityFilter.js
- apps/health_alerts/templates/health_alerts/health_alert_index_page.html
- apps/hip/templates/hip/static_page.html
- apps/hip/templates/includes/health_alert_legend.html
- docs/deploy.md
- docs/provision.md
- hip/static/js/index.js
- hip/static/styles/bundle.scss
- hip/static/styles/includes/health_alert_legend.scss
- hip/static/styles/pages/health_alert_index_page.scss
I just noticed that on my new laptop, I had not configured tabs to be converted to spaces (:cone-of-shame:).
First commit: 
* converts tabs to spaces in the files I have committed
Second commit:
* Adds the hoverable legend on desktop only (as an include, so as not to clutter the template, and so it might be reused for the home page recent updates section if needed later)
* Aligns the year headings properly, makes them bold and gray
* Makes the table column widths match the mockup better (last 2 columns smaller than the first)
* Makes the table header slightly taller and vertical aligns the content inside of them
* Makes the topic 18px font, slightly larger than the other 2 columns
* Makes priority uppercase
Third commit:
* Styles the filter (no shadow, aligned properly with other items on …
> HP-64: Health alerts legend, filter widget and design tweaks

- apps/disease_control/templates/includes/disease_control_card.html
https://caktus.atlassian.net/browse/HP-83
- only displays a disease's emergent date range if the disease is emergent
- uses the `DiseasePage.emergent_date_range()` method for displaying the emergent date range in the template
> [HP-83] Only Show Emergent Date Range If Disease Is Emergent

- README.md
- requirements/dev/dev.in
- requirements/dev/dev.txt
The current sync commands puts the media folders inside "PROJECT/media/media" but our
code looks for files in "PROJECT/media". The latest version of invoke-kubesae allows you
to specify a `bucket-path` parameter which fixes that for us.
> Fix sync-media-to-dev commands

- apps/disease_control/templates/disease_control/disease_page.html
- apps/hip/wagtail_hooks.py
- hip/static/styles/_mixins.scss
- hip/static/styles/_variables.scss
- hip/static/styles/common.scss
- hip/static/styles/icons.scss
- hip/static/styles/includes/disease_control_card.scss
- hip/static/styles/includes/header.scss
- hip/static/styles/pages/disease_page.scss
- hip/static/styles/pages/static_page.scss
This adds styles for the "at a glance" and "current recommendations" boxes at the top, and adds icons next to the documents at the bottom of the page. (Note this is a change from the AC... instead of showing thumbnails for the patient/community resources, we are just listing them with icons next to them)
Still needed:
> HP-25-styling Begin styling the disease page

- apps/hip/wagtail_hooks.py
- hip/static/js/common.js
- hip/static/styles/common.scss
Fix to make sure wagtail hook external links have the same font-family as the result of the site (override Font Awesome Free) font family.
> fix text inside of wagtail hook

- apps/disease_control/models.py
by adding it to the `DiseasePage`'s `content_panels`.
> Allow DiseasePage.description To Be Editable In Wagtail Again

- hip/settings/base.py
https://caktus.atlassian.net/browse/HP-52
This pull request limits `Document` uploads to files that have either a .pdf, .png, or a .jpg extension. As a note, I find it surprising that the error only shows up after the document claims to have uploaded (step 2), but it's Wagtail's functionality, so I decided to not change it, and we can see how it does in QA.
> [HP-52] Limit Documents To PDF, PNG, JPG

- apps/health_alerts/static/js/healthAlertFilter.js
- apps/hip/templates/includes/health_alert_table_header.html
https://caktus.atlassian.net/browse/HP-100
This moves the table header to be right after the first year, and it moves our "no alerts found" row to be just under the table header row as well. I don't think that there is any situation where the "no alerts row" will actually show up now on the main health alerts page.
> HP-100 Move the header below the first year

- apps/emergency_response/tests/factories.py
A previous pull request incorrectly named the `EmergencyResponsePageFactory` as `EmergentHealthTopicsPageFactory` due to copy/pasting.
> Rename Incorrectly Named Factory

- apps/disease_control/templates/disease_control/disease_and_condition_detail_page.html
- apps/health_alerts/templates/health_alerts/health_alert_list_page.html
- apps/health_alerts/templates/health_alerts/health_alert_subscriber.html
- hip/urls.py
https://caktus.atlassian.net/browse/HP-109
- updates the link from the disease detail page to the health alerts signup page to be the real link
- updates other template files that have a link to the health alerts signup page to use Django's `url` template tag
- adds a trailing slash at the end of the `health_alert_subscriber` URL path
> [HP-109] Fix Health Alert Signup On Disease Page

- apps/hip/templates/includes/search_result_card.html
https://caktus.atlassian.net/browse/HP-112
This pull request adds the link icon and the word 'PAGE' to each card in the search results that is not a health alert page.
> [HP-112] Disaply Link Icon For Non-Health-Alert Pages

- apps/emergency_response/templates/includes/partner_login_card.html
- apps/hip/templates/includes/header.html
This pull request changes hard-coded login & logout URLs in templates to use Django's `url` template tag with the URL's name.
> Use Django's Url Template Tag For Login & Logout URLs In Templates

- apps/hip/templates/includes/header.html
- apps/hip/templates/includes/mobile_search_modal.html
https://caktus.atlassian.net/browse/HP-111
This pull request makes the search icon clickable both in the header and on the search modal.
Based on the team discussion about removing the search bar, I left the search icon alone on the search results page.
> [HP-111] Make Search Icon Clickable

- apps/hip/templates/includes/header.html
- hip/static/styles/icons.scss
This pull request makes the logout icon show up in the template by using the correct mixin in the `icons.scss` file. Also, the icon now has a little padding, in order to match the wireframe.
> Make Logout Button Icon Show Up In Template

- apps/hip/templates/registration/login.html
- Remove back button and add sidebar back to desktop
As a team we have decided to keep the `sidebar` as visible on the `login.html` page and the `password_reset.html` page. The `< Back` button has been removed from the `login.html`. Both the `login.html` and `password_reset.html` page should fully resemble each other.
> HP-122 & HP-124

- apps/hip/models.py
This pull request makes the `HomePage` and `StaticPage` inherit `content_panels` from `HipBasePage`, which adds the search description to the fields that the CMS user can edit in the content panel.
> Add Search Description to HomePage and StaticPage Content Panels

- apps/auth_content/templates/auth_content/closed_pod_home_page.html
https://caktus.atlassian.net/browse/HP-135
This pull request removes the 'is-size-7-touch' CSS class from the contact info icon on the Closed POD homepage, so its height matches the height of the button with the text.
> [HP-135] Give Icon Same Height As Text

- apps/hip/templates/hip/static_page.html
- apps/reports/templates/reports/data_report_detail_archive_detail_page.html
- apps/reports/templates/reports/data_report_detail_page.html
- hip/static/styles/pages/data_report_archive_detail_page.scss
- hip/static/styles/pages/data_report_detail_page.scss
- moves the 'before_staticpage_content' block to within the main column of the `StaticPage`
- moves the CSS class for the report detail and report archive detail pages to be on the main column of the template, rather than a parent of the columns. This way, the styles are only applied to the main column, and not the right nav.
> [HP-139] Report Detail Page Rightnav Styles

- hip/static/styles/_mixins.scss
https://caktus.atlassian.net/browse/HP-132
This pull request takes away the limit for a paragraph's maximum width. After checking all affected pages (`DataReportDetailPage`, `PCWMSAHomePage`, `ClosedPODHomePage`, also a number of pages with a right-side navbar, like the `StaticPage`), it seems that paragraphs are already limited in their width by their parent, so this restriction doesn't seem necessary.
> [HP-132] Don't Limit Paragraph Width

- apps/reports/models.py
- apps/reports/templates/reports/data_report_list_page.html
- apps/reports/tests/test_models.py
https://caktus.atlassian.net/browse/HP-138
This pull request changes the external reports' `last_updated` value sent to the template to be a date, to match internal reports' `last_updated` value.
> [HP-138] Format External Report Dates

- apps/auth_content/models.py
This pull request explicitly defines `PCWMSAHomePage`' children to be either `StaticPage`s or `ListPage`s.
> Allow PCWMSAHomePage To Have Children

- apps/hip/models.py
Similar to #129, this pull request explicitly defines `ListPage`s' children to be either `StaticPage`s or `ListPage`s.
> Allow ListPage To Have Children

- apps/hip/forms.py
- apps/hip/tests/factories.py
- apps/hip/tests/test_forms.py
- hip/settings/deploy.py
https://caktus.atlassian.net/browse/HP-145
First commit turns of error emails since we get them through sentry (thought I did this before, but obviously I didn't!)
Second commit changes our Document form to only validate the file if it has changed. If a user is only editing the title, for example, we shouldn't even try to validate the existing file.
> HP-145: Don't try to validate file if it hasn't changed and turn off error emails

- apps/disease_control/models.py
`DiseaseControlListPage`s may now have children that are `DiseaseAndConditionListPage`s, `StaticPage`s, or `ListPage`s. Also, there may only be 1 `DiseaseAndConditionListPage` for a `DiseaseControlListPage`.
> Update DiseaseControlListPage Children

- apps/hip/static/js/sidebar.js
https://caktus.atlassian.net/browse/HP-150
This pull request updates the `getParentSidebarLink()` function to only return a sidebar element if it is found.
> HP-150 Highlight Sidebar Links For Nested Pages

- apps/reports/templates/reports/data_report_detail_page.html
https://caktus.atlassian.net/browse/HP-151
This pull request gives the  'View Previous Years' link a left-padding to match the `<h2>` left-padding, in case the `<h2>` contents are so long that they go onto a second line. A future pull request will attempt to make the space between the left sidebar and the main content consistent across the site.
> [HP-151] Report Pages Alignment: Part I

- apps/common/models.py
- apps/disease_control/models.py
- apps/hip/models.py
https://caktus.atlassian.net/browse/HP-158
- hides the "Show in menus" field from all pages that inherit from `HipBasePage`
- makes `StaticPage`, `ListPage`, `DiseaseControlChildStaticPage`, and `DiseaseControlChildListPage` also inherit the promote tab fields from `HipBasePage`
> [HP-158] Hide Promote Tab "Show in menus"

- apps/disease_control/models.py
This pull request defines children of `DiseaseControlChildListPage`s and `DiseaseControlChildListPage`s to be `StaticPage`s or `ListPage`s.
> Define Children Of DiseaseControlChildStaticPage And DiseaseControlChildListPage

- apps/common/tests/test_utils.py
- apps/common/utils.py
This pull request gives superusers permission to the Closed POD contact information page, regardless of whether they are in the "Closed POD" `Group` or not, by making them pass the `closedpod_user_check`.
> Superusers Pass closedpod_user_check

- requirements/base/base.txt
- requirements/dev/dev.txt
This pull request upgrades wagtial to its [newest bugfix version](https://docs.wagtail.io/en/stable/releases/2.12.4.html).
> Upgrade Wagtail

- deploy/host_vars/staging.yml
Do not merge until philly updates their DNS to point hip-staging.phila.gov at our load balancer.
> HP-156 New staging domain

- apps/common/context_processors.py
- apps/common/tests/test_context_processors.py
- apps/hip/templates/includes/footer.html
- hip/settings/base.py
https://caktus.atlassian.net/browse/HP-169
This pull request makes the links in the footer functional by:
- setting footer links to URLs
- setting the PDF URL to the value returned by a new context processor, `right_to_know_pdf_url`
Note: these links assume that the appropriate pages have been created in Wagtail.
From a user perspective, it would have been better to give Wagtail users the ability to set the footer URLs, but we're running out of hours, so they are hard-coded for now. Perhaps in the future these links can become editable in Wagtail.
> [HP-169] Footer Links

- apps/auth_content/migrations/0010_auto_20210420_1916.py
- apps/auth_content/tests/test_views.py
- apps/auth_content/views.py
https://caktus.atlassian.net/browse/HP-170
This pull request adds `closedpod_home_url` to the `closedpod_contact_information` view template context.
Also, this pull request fixes the migration clash in the `auth_content` app.
> [HP-170] Closed POD Home Page Left Nav Link

- .github/workflows/deploy.yml
- .github/workflows/test.yml
This pull request specifies 3.8.9 as our version of Python in our GitHub actions files, to avoid the regression in the 3.8.10 release (https://bugs.python.org/issue44061).
> Fix GitHub Actions

- hip/templates/base.html
https://caktus.atlassian.net/browse/DIS-1688
Please note (here)[https://standards.phila.gov/docs/development/analytics.html#analytics-tracking-for-webpages] bullet point 3.
This PR:
- updates `base.html` adding the google analytics script and iframe object. 
- Google Analytics should be present on each page.
- Analytics should work on `hip-staging.phila.gov`, but not `hip.caktus-built.com`.
> DIS-1688 - Add google analytics 

- apps/common/tests/test_utils.py
- apps/common/utils.py
- apps/hip/forms.py
- apps/hip/templates/registration/login.html
- apps/hip/tests/test_forms.py
- apps/hip/tests/test_views.py
- apps/hip/views.py
https://caktus.atlassian.net/browse/DIS-1678
This pull request restricts Single Sign On users from logging in with a username & password by:
- adding an `is_sso_user()` utility function that determines if a user is an SSO user
- adding an `HIPAuthenticationForm`, which requires users to be non-SSO users when validating their data
- using the `HIPAuthenticationForm` on the `HIPLoginView`
- showing errors for each of the fields of the `HIPAuthenticationForm` in the front-end, rather than hard-coding an error message
> [DIS-1678] Restrict SSO Users From Logging In With Username & Password

- apps/hip/tests/test_views.py
- apps/hip/views.py
- hip/urls.py
https://caktus.atlassian.net/browse/DIS-1679
This pull request redirects requests for the Wagtail login page and Django admin login page to go to the regular login page. The `next` URL parameter, if present, persists to the regular login page.
> [DIS-1679] Use Regular Login Page For Wagtail and Django Admin

- apps/hip/forms.py
- apps/hip/tests/test_forms.py
https://caktus.atlassian.net/browse/DIS-1648
This pull request temporarily comments out the change from #181, which forced phila.gov users to use SSO. The plan is to uncomment this code once SSO permissions issues are sorted out, hopefully early next week.
> [DIS-1695] Temporarily Comment Out SSO User Changes

- apps/emergency_response/templates/includes/partner_login_card.html
- apps/hip/templates/includes/header.html
- apps/hip/templates/registration/login.html
- hip/static/styles/common.scss
- hip/static/styles/includes/partner_login_card.scss
https://caktus.atlassian.net/browse/DIS-1680
- separates the login page vertically by using a divider `<div>` element, so that the username/password login is on the left side, and the SSO login is on the right side
- updates the header link to say 'Log In', rather than 'Partner Log In'
- updates the `partner_login_card.html` link to say 'Log In', rather than 'Partner Log In'
- removes styles for the partner login card, which are no longer needed, since they were previously used to make sure the 'Partner Log In' button was not too wide
> [DIS-1680] Update Login Page Design

- apps/emergency_response/templates/includes/partner_login_card.html
https://caktus.atlassian.net/browse/DIS-1699
This pull request updates the header on the partner login card to be 'Log In', rather than 'Partner Log In'.
> [DIS-1699] Update Partner Login Card Header Text

- apps/notifications/apps.py
- apps/notifications/forms.py
- apps/notifications/models.py
- apps/notifications/templates/notifications/notification_signup.html
- apps/notifications/tests/test_views.py
- apps/notifications/views.py
- hip/settings/base.py
- hip/static/styles/bundle.scss
- hip/static/styles/includes/notification_signup.scss
- hip/urls.py
https://caktus.atlassian.net/browse/DIS-1674
This pull request makes empty views for new forms (internal alerts form, community response notifications form, opioid overdose notifications form, code blue/code red notifications form, public health preparedness notifications form) by creating a `generic_notification_signup` view, and using it to render each of the new forms. The content of the forms (fields, logic, presentation, tests) will be completed in DIS-1700.
> [DIS-1674] Part I: Make Empty Views For New Forms

- apps/common/tests/test_utils.py
- apps/common/utils.py
- apps/notifications/templates/notifications/notification_signup.html
- apps/notifications/tests/test_views.py
- apps/notifications/views.py
https://caktus.atlassian.net/browse/DIS-1701
Currently, submitting the internal alerts form relies on the request's `HTTP_REFERER` parameter to determine the user's previous URL. This works ok, but in case the user submits the internal alerts form and gets the form back with errors, then the `HTTP_REFERER` header is set to the form's URL, meaning that submitting the form will bring the user back to the form.
This pull request: 
- adds a `get_next_url_from_request()` utility function for getting the next URL from request parameters
- uses the `get_next_url_from_request()` function to determine the success URL and close URL for the internal alerts form
- adds a form `action` with the `next` URL parameter to the `notification_signup.html` template
> [DIS-1701] Part III: Add 'next' URL Parameter For Forms

- hip/static/styles/wagtail_styles.scss
In order to make the Wagtail interface a little easier to use, each row of tables are now aligned with each other at the top, so we avoid some table cells being above and others being below, like in the screenshot.
> Align Each Table Row In Wagtail At The Top

- hip/static/js/common.js
https://caktus.atlassian.net/browse/DIS-1715
This pull request updates the `addExternalLinkIconsAndDomain()` function in `common.js`, so that links to URLs on the same domain don't display the external link icon, even if they have the "external-linktype" CSS class.
> [DIS-1715] Remove External Link Icon From URLs To Same Domain

- apps/disease_control/templates/disease_control/disease_and_condition_list_page.html
- apps/disease_control/templates/disease_control/disease_control_list_page.html
- apps/health_alerts/templates/health_alerts/health_alert_list_page.html
- apps/hip/templates/hip/static_page.html
- apps/reports/templates/reports/data_report_detail_page.html
- apps/reports/templates/reports/data_report_list_page.html
- hip/static/styles/bundle.scss
- hip/static/styles/pages/disease_and_condition_list_page.scss
- hip/static/styles/pages/disease_control_list_page.scss
- hip/static/styles/pages/health_alert_list_page.scss
https://caktus.atlassian.net/browse/DIS-1723
This pull request makes the headers on the following pages match the header on the Emergency Response page:
- disease control list page (/disease-control/)
- diseases and conditions list page (/disease-control/diseases-and-conditions/)
- data reports list page (/data-reports-statistics/)
- health alerts page (/health-alerts/)
Note: I also removed the ability to have a double breadcrumb on data reports detail pages.
> [DIS-1723] Make Headers Match Emergency Response Header

- apps/users/apps.py
- deploy/deploy-cluster.yml
- deploy/group_vars/all.yml
- deploy/stack/eks-no-nat.yml
https://caktus.atlassian.net/browse/DIS-1669
- updates the `apps.users.apps.UsersConfig` class to have a `ready()` method, which imports all of the signals in the `users` app. This is a change that we should have made when upgrading to Django3.2, but it looks like no one noticed that the signals stopped working, since we weren't sending the logs anywhere.
- adds a task to install the "AWS for Fluent Bit" helm chart for the cluster, based on Colin's recommendation in our Slack channel. This task was run with `inv deploy.playbook deploy-cluster.yml`  
The Django logs are now being sent to AWS CloudWatch, and can be seen here: https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:logs-insights .
> [DIS-1669] Send Logs To AWS CloudWatch

- hip/settings/base.py
https://caktus.atlassian.net/browse/DIS-1727
By default, [small files uploaded through the admin/Wagtail use Django's `django.core.files.uploadhandler.MemoryFileUploadHandler`](https://docs.djangoproject.com/en/3.2/topics/http/file-uploads/#where-uploaded-data-is-stored), and larger files use Django’s `django.core.files.uploadhandler.TemporaryFileUploadHandler`. Since the `MemoryFileUploadHandler` holds the contents of the file in memory, an uploaded file using the `MemoryFileUploadHandler` does not have a `temporary_file_path()` method, which is a problem for our `ValidateFileTypeForm.clean_file()` method, which tries to pass a temporary path to our `scan_pdf_for_malicious_content()` function.
It looks like our scanning ability requires having a file path to a PDF file, so this pull …
> [DIS-1727] Fix Document Upload For Small Documents

- apps/auth_content/templates/auth_content/big_cities_home_page.html
- apps/auth_content/templates/auth_content/closedpod_contact_information.html
- apps/posters/templates/posters/poster_detail_page.html
- apps/posters/templates/posters/poster_list_page.html
https://caktus.atlassian.net/browse/DIS-1726
Following up on the work in #210, this pull request makes headers on the following pages match the header on the Emergency Response page:
- posters list page (/posters/)
- poster detail page (for example: /posters/prevent-the-spread-of-norovirus/)
- closed POD contact page (/closed-pod/closedpod-contact-information/)
- big cities homepage (/big-cities-public-health-preparedness/)
As a note, I also removed the double message on the closed POD contact information page.
> [DIS-1726] More Consistent Headers On Site

- docs/hosting-services.md
https://caktus.atlassian.net/browse/DIS-1669
This pull request adds documentation about how error logs are handled in AWS, including using a CloudWatch alarm, and how to investigate further when notified of an error.
> [DIS-1669] Documentation

- deploy/host_vars/staging.yml
To prepare for merging #193 and having the site go live, this pull request removes the caktus-built.com domain from the staging site.
> Remove caktus-built.com Domain For Staging Site

- deploy/requirements.yml
This pull request downgrades the version of `ansible-role-django-k8s` to 1.3.0, so deploys do not fail on a rabbitmq error:
```
failed: [staging] (item={'name': 'rabbitmq.yaml.j2', 'state': 'absent'}) => changed=false 
ansible_loop_var: item
item:
name: rabbitmq.yaml.j2
state: absent
msg: Failed to find exact match for rabbitmq.com/v1beta1.RabbitmqCluster by [kind, name, singularName, shortNames]
```
> Fix Deployment Issue With RabbitMQ

- .gitignore
- Dockerfile
- hip/settings/base.py
- hip/settings/deploy.py
- package.json
This PR makes adjustments after previous merge of this work caused develop branch to fail. Previous PR can be seen [here](https://github.com/caktus/philly-hip/pull/240).
These changes primarily remove lines dependent on `webpack-stats.json`, with some extra unnecessary Webpack-loader related code also removed.
> Fix Upgrade NodeJS from version 12 to version 16

- deploy/group_vars/all.yml
- deploy/requirements.yml
- requirements/dev/dev.in
- requirements/dev/dev.txt
Update web cluster, k8s, helm chart, and cert-manager
Includes:
- Update Kubernetes v1.20 -> v1.22
- Update NGINX Ingress Controller 3.39.0 -> 4.0.19
-  Update Django-k8s v1.3.0 -> v1.5.0
- Update certificate manager v1.6.1 -> v1.7.2
- Update fluentbit chart version v0.1.11 -> v0.1.18
- Update ansible v2.10.5 -> v5.9.0
- Update jinga2 v2.11.3 -> v3.0.3
Caktus Hosting Services ticket 
- caktus/caktus-hosting-services#192
> 192 update kubernetes [production-hot-fix]

- .gitignore
This PR adds `webpack-stats.json` to the `.gitignore` file, so that we don't accidentally commit it.
> Ignore webpack-stats.json

- hip/static/styles/pages/static_page.scss
[Ticket](https://caktus.atlassian.net/browse/DIS-1801?atlOrigin=eyJpIjoiMjJkODI4NzdmMDhmNGJlMzhkNDhkODNhNzM3M2E5NjgiLCJwIjoiaiJ9)
This PR:
- Changes the font color for headings in the Right-hand nav (as on the Posters page) to provide better contrast with the white background
- Adds an arrow to indicate the active heading, as contrast between active heading color and non-active heading color was too low
Note: The arrow indicator was not requested, and can be removed or altered if requested. It or some other non-color-based indicator will be required for full accessibility
> [DIS-1801] Improves color contrast of right-hand nav and adds arrow indicator

- apps/hip/templates/includes/poster_card.html
[Ticket](https://caktus.atlassian.net/browse/DIS-1799?atlOrigin=eyJpIjoiOGQ4YTJiYTBmMzEzNDI0NjliYWY2OTMzZTJmN2FjZTYiLCJwIjoiaiJ9)
This PR adds the text "(PDF)" after each poster card on the Posters page.
> [DIS-1799] Adds (PDF) to poster titles

- hip/static/styles/pages/base.scss
- hip/templates/base.html
[Ticket](https://caktus.atlassian.net/browse/DIS-1798?atlOrigin=eyJpIjoiNjMzZDEwYjBkMDA0NDZmMzlhNzRjOWJiMjgxZTI4YjkiLCJwIjoiaiJ9)
This PR 
- Adds an `<h1>` element to every page across the site. It is the same on every page, "Health Information Portal (HIP)".
- Adds a `visually-hidden` class, so that it can be hidden from sighted users, but visible to users with screen readers.
Note: It may be worth revisiting the idea of adding a unique `<h1>` tag to each page (ex. "Health Alerts", "Data and Reports", "Disease Control", etc). For now, this solution is the one requested in the ticket, where all pages have the same `<h1>` element.
> [DIS-1798] Adds <h1> tag to base.html, which applies to every page across the site

- requirements/base/base.txt
- requirements/dev/dev.txt
This pull request upgrades Django to the latest bugfix version (3.2.16), to include [one more Django bugfix](https://docs.djangoproject.com/en/4.1/releases/3.2.16/).
> Upgrade Django To Latest Bugfix Version

- requirements/base/base.txt
- requirements/dev/dev.txt
Upgrades the Django version to avoid a zero day vulnerability. See [here ](https://www.djangoproject.com/weblog/2023/feb/01/security-releases/)for more info.
> Upgrade Django version

- deploy/group_vars/all.yml
- deploy/requirements.yml
https://app.clickup.com/t/8677fztpa
```
❯ inv deploy.install
❯ inv deploy.playbook deploy-cluster.yml
❯ kubectl -n kube-system get cronjob
NAME          SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
descheduler   */2 * * * *   False     0        34s             3m54s
```
```
❯ inv staging deploy.playbook -n deploy-cluster.yml
❯ kubectl -n ingress-nginx get pod -o wide
NAME                                        READY   STATUS    RESTARTS   AGE    IP           NODE                         NOMINATED NODE   READINESS GATES
ingress-nginx-controller-7b454df556-clllc   1/1     Running   0          95s    10.0.14.73   ip-10-0-12-45.ec2.internal   <none>           <none>
ingress-nginx-controller-7b454df556-t87fq   1/1     Running   0          115s   10.0.10.8    ip-10-0-9-16.ec2.internal …
```
> Deploy descheduler, upgrade Helm charts

- apps/health_alerts/models.py
- apps/health_alerts/tests/test_models.py
ClickUp ticket: https://app.clickup.com/t/8684y6f05
Previously, the `HealthAlertDetailPage.alert_file` field was optional, but serving a health alert page redirected users to the `HealthAlertDetailPage`’s `alert_file`’s URL. As a result, loading a `HealthAlertDetailPage` with an empty `alert_file caused a server error.
Now, if a `HealthAlertDetailPage` has an empty `alert_file`, a generic 404 page will be returned (whether in the Wagtail preview panel, or on the site).
Note: it appears that this server error can only be triggered for Wagtail users. Regular (non-authenticated) users can click on the health alerts from the health alerts list page ([which only have a link if the `HealthAlertDetailPage` has an `alert_file`](https://github.com/caktus/philly-hip/blob/develop/apps/hip/templates/i …
> Avoid Server Error On Health Alerts Without Alert File

- .github/workflows/deploy.yml
- requirements/base/base.in
- requirements/base/base.txt
- requirements/dev/dev.in
- requirements/dev/dev.txt
This fixes an error building PyYAML 5.4.1, which picked up the new cython 3, with which it is not compatible. Philly-hip doesn't use PyYAML directly, it is needed by deploy-related packages, including AWS CLI.
`PyYAML == 6.0.1` is now pinned in `base.in`.
> Fix build (pyyaml)

- Dockerfile
This PR enables reloading workers after a specified amount of managed requests - `1000` - to avoid memory leaks.
> Avoid Memory Leaks [No ClickUp ticket]

- .github/workflows/test.yml
- Dockerfile
- README.md
- apps/reports/tests/test_models.py
- deploy/deploy-cluster.yml
- deploy/group_vars/all.yml
- deploy/requirements.yml
- docker-compose.yml
- requirements/base/base.in
- requirements/base/base.txt
- requirements/dev/dev.in
- requirements/dev/dev.txt
This PR serves as documentation/reference for the Kubernetes upgrade of the `Philly Hip` cluster. The sites on this cluster are all the [staging](https://hip-staging.phila.gov/) and [production](https://hip.phila.gov/).
**Ingress Nginx**
```
> helm -n ingress-nginx list                                    
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   ingress-nginx   7               2024-05-14 10:21:08.299385 -0400 EDT    deployed        ingress-nginx-4.9.1     1.9.6
```
**Cert Manager**
```
>  helm -n cert-manager list                                    
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART …
```
> Kubernetes Upgrade v1.25 -> v1.29 

- deploy/group_vars/all.yml
- deploy/requirements.yml
- requirements/deploy/deploy.in
- requirements/deploy/deploy.txt
This PR updates the container Instance size and New Relic to avoid the following error 
```
kubectl -n hip-staging logs -lapp=app
File "/usr/local/lib/python3.11/site-packages/newrelic/packages/wrapt/__init__.py", line 10, in <module>
from .decorators import (adapter_factory, AdapterFactory, decorator,
File "/usr/local/lib/python3.11/site-packages/newrelic/packages/wrapt/decorators.py", line 34, in <module>
from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
```
> Update New Relic and Container Instance Size

- deploy/group_vars/all.yml
Some people at Wiz wrote a great post about this: https://www.wiz.io/blog/ingress-nginx-kubernetes-vulnerabilities
_Ingress Nginx version update (and other packages)_
**Ingress Nginx**
```sh
> helm -n ingress-nginx list 
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx   ingress-nginx   10              2025-03-26 10:11:05.698095 -0400 EDT    deployed        ingress-nginx-4.11.5    1.11.5  
```
**Cert Manager**
```sh
> helm -n cert-manager list
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
cert-manager    cert-manager    8               2025-03-26 10:12:28.163548 -0400 EDT    deployed …
```
> Update Ingress Nginx Chart

- Makefile
- README.md
- hip/static/js/bundles/main.js
- hip/templates/404.html
- hip/templates/500.html
- hip/urls.py
As noted in the ClickUp ticket, the site is currently not defining a template to use for 404 (or a 500) status code responses. As a result, the page for such responses looks not great.
It turns out the code actually has functions for handling 404 and 500 status-code responses, but they weren't hooked up as Django expected, and the templates (404.html and 500.html) didn't exist.
- hooks up the handlers for 404 and 500 status-code responses [as expected by Django](https://docs.djangoproject.com/en/4.2/topics/http/urls/#error-handling)
- adds the necessary HTML templates (404.html and 500.html)
To test locally:
- set the following in your `local.py` settings file:
```
DEBUG=False
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
```
To see the …
> Use Custom 404 And 500 Templates

- README.md
- deploy/deploy-runner.yml
- docs/deploy.md
The GitHub runner needs two scopes to run: `repo` and `org:admin`.
```
> kubectl -n github-runner get pod                        
NAME                                     READY   STATUS    RESTARTS   AGE
arc-gha-rs-controller-5fd5c6b567-9p944   1/1     Running   0          8m18s
arc-runner-set-f577755c-listener         1/1     Running   0          8m10s
```
Error message in controller pod:
```
2025-06-10T14:31:28Z    ERROR   Reconciler error        {"controller": "autoscalingrunnerset", "controllerGroup": "actions.github.com", "controllerKind": "AutoscalingRunnerSet", "AutoscalingRunnerSet": {"name":"arc-runner-set","namespace":"github-runner"}, "namespace": "github-runner", "name": "arc-runner-set", "reconcileID": "f4c8328b-81fd-4c6b-88a7-598e36a95fc5", "error": "failed to get runner …
```
> Deploy GitHub runner with `repo` and `org:admin` scoped PAT
