caktus/philly-hip

requirements/dev/dev.txt
I forgot to run pip-compile locally before generating the PR in #7
=> Update the actual requirements file

apps/hip/templates/home.html, hip/templates/base.html
- Point to correct main.js file
- fix header tag on home.html
=> HP-9 Cleanup 

hip/templates/base.html
... so logged in users can easily get to CMS admin
https://docs.wagtail.io/en/stable/topics/writing_templates.html#wagtail-user-bar
=> Add wagtail user bar

apps/hip/templates/hip/static_page.html, hip/templates/base.html
https://caktus.atlassian.net/browse/HP-33
=> HP-33 Remove left sidebar and add back button

apps/hip/static/js/rightScrollNav.js, apps/hip/templates/hip/static_page.html, apps/hip/templates/includes/right_scroll_nav.html, hip/static/styles/_mixins.scss, hip/static/styles/pages/static_page.scss
https://caktus.atlassian.net/browse/HP-32
... and add smooth scrolling for fun! :)
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView
=> HP-32 Get right-scroll-nav to change colors appropriately

apps/hip/static/js/header.js, apps/hip/templates/includes/sidebar.html, hip/static/styles/_mixins.scss, hip/static/styles/includes/mobile_search_modal.scss, hip/static/styles/includes/sidebar.scss
https://caktus.atlassian.net/browse/HP-51
This PR makes the sidebar a modal on mobile when the hamburger icon is clicked. This modal shares the same functionality as the mobile search modal when the search icon is clicked.
=> HP-51 Sidebar - Full Screen Modal On Mobile

apps/hip/static/js/sidebar.js
https://caktus.atlassian.net/browse/HP-65
=> HP-65 Only activate sidebar if element exists

apps/health_alerts/models.py, apps/hip/templates/hip/home_page.html, hip/static/styles/_colors.scss, hip/static/styles/_mixins.scss, hip/static/styles/common.scss, hip/static/styles/icons.scss, hip/static/styles/pages/base.scss, hip/static/styles/pages/health_alert_index_page.scss, hip/static/styles/pages/home_page.scss
https://caktus.atlassian.net/browse/HP-48
https://caktus.atlassian.net/browse/HP-50
=> HP 48 & HP 50

apps/health_alerts/templates/health_alerts/health_alert_index_page.html, hip/static/styles/_colors.scss, hip/static/styles/pages/health_alert_index_page.scss
https://caktus.atlassian.net/browse/HP-68
=> HP-68 Stripe tables ourselves so we can reset colors (and add spacing)

apps/health_alerts/models.py
Sentry error: https://sentry.io/organizations/caktus/issues/2233559523/
=> Fix HealthAlert page 500 error

apps/hip/tests/test_utils.py, apps/hip/utils.py
https://caktus.atlassian.net/browse/HP-59
=> HP-59 - Remove Documents from  get_most_recent_objects definition

apps/disease_control/models.py, apps/disease_control/templates/disease_control/disease_page.html, apps/disease_control/templates/disease_control/diseases_and_conditions_page.html, apps/disease_control/templates/includes/disease_control_card.html, apps/disease_control/utils.py, apps/hip/templates/includes/breadcrumb.html, hip/static/styles/_colors.scss, hip/static/styles/bundle.scss, hip/static/styles/includes/breadcrumbs.scss, hip/static/styles/includes/disease_control_card.scss
This PR:
1) Styles the `Disease and Conditions` page
2) Adds the breadcrumb component. This component is also added to the `Disease and Conditions` page and the `DiseasePage`.
https://caktus.atlassian.net/browse/HP-24
=> HP-24 Part 2 - Style Disease and Conditions page & Add Breadcrumb

apps/hip/static/js/common.js, apps/hip/templates/includes/header.html, hip/static/styles/includes/header.scss
https://caktus.atlassian.net/browse/HP-77
This works OK, but I'm not 100% sure it is the right way to do this. I tried `position: sticky` as well, but couldn't get that to work.
Let me know if there are better solutions.
=> HP-77 Fix navbar header on mobile

apps/health_alerts/templates/health_alerts/health_alert_index_page.html, apps/hip/templates/includes/right_scroll_nav.html
https://caktus.atlassian.net/browse/HP-79
=> HP-79 Health Alerts Anchor Alignment

apps/hip/static/js/sidebar.js, apps/hip/templates/includes/breadcrumb.html, hip/static/styles/includes/breadcrumbs.scss
https://caktus.atlassian.net/browse/HP-85
=> HP-85 Use breadcrumb navigation to set "is-active" sidebar link

apps/disease_control/templates/disease_control/disease_page.html, hip/static/styles/pages/disease_page.scss
https://caktus.atlassian.net/browse/HP-89
=> HP-89 Align View Alerts link

apps/disease_control/models.py, apps/disease_control/templates/disease_control/disease_page.html, apps/health_alerts/templates/health_alerts/health_alert_index_page.html, hip/static/styles/pages/disease_page.scss, hip/static/styles/pages/health_alert_index_page.scss
https://caktus.atlassian.net/browse/HP-97
This
* orders the health alerts on the disease page properly
* makes mobile margins a little narrower
* makes the topic column of health alerts a little wider
=> HP-97, part 2

apps/hip/templates/includes/header.html, hip/static/styles/_variables.scss, hip/static/styles/includes/header.scss, hip/static/styles/includes/sidebar.scss
- https://caktus.atlassian.net/browse/HP-82
- https://caktus.atlassian.net/browse/HP-78
- Also fix for responsive spacing of header nav buttons
=> HP-82 & HP-78

apps/health_alerts/models.py, apps/health_alerts/static/js/healthAlertFilter.js, apps/health_alerts/templates/health_alerts/health_alert_index_page.html, apps/hip/templates/includes/health_alert_table_row.html, hip/static/js/index.js
https://caktus.atlassian.net/browse/HP-80
=> HP-80 Remove priority filter from health alerts

apps/health_alerts/static/js/healthAlertFilter.js
https://caktus.atlassian.net/browse/HP-103
...to prevent doing things on the Disease&Condition page that we only want to do on the
main Health Alerts page.
=> HP-103 Break down functions more discretely

.github/workflows/test.yml, webpack-stats.json
... so that we don't have to checking webpack-stats.json
=> Trial of running npm build on CI

apps/emergency_response/templates/includes/partner_login_card.html
https://caktus.atlassian.net/browse/HP-108
=> [HP-108] Remove 'Exercise Partners' From Partner Login Card Template

apps/hip/templates/includes/search_result_card.html
https://caktus.atlassian.net/browse/HP-113
=> [HP-113] Add Padding Between Icon And Text In Search Results Cards

apps/hip/templates/includes/sidebar.html, hip/static/styles/common.scss, hip/static/styles/icons.scss
https://caktus.atlassian.net/browse/HP-114
This pull request adds the link to the login page into the mobile view sidebar, and shows a working logout link in the mobile view sidebar for users who are logged in.
=> [HP-114] Add Login Page Link To Sidebar

apps/hip/templates/includes/header.html, apps/search/templates/search/search.html
https://caktus.atlassian.net/browse/HP-118
- removes search bar on search results page
- adds the value of the search query into the search bar input in the header
=> [HP-118] Remove Second Searchbar

apps/hip/forms.py, hip/settings/base.py
https://caktus.atlassian.net/browse/HP-99
=> HP-99 Show user error message before file gets added to repository

apps/auth_content/templates/auth_content/closed_pod_home_page.html
https://caktus.atlassian.net/browse/HP-129
This pull request decreases the padding on the different sections of the Closed POD homepage, and makes sure that the padding/margin for each section match the other sections.
=> [HP-129] Closed POD Homepage Padding

apps/hip/templates/includes/poster_card.html, hip/static/styles/pages/poster_list_page.scss
https://caktus.atlassian.net/browse/HP-137
=> HP-137 Decrease horizontal padding for poster titles

hip/static/styles/_mixins.scss, hip/static/styles/pages/data_report_archive_list_page.scss, hip/static/styles/pages/data_report_list_page.scss, hip/static/styles/pages/disease_and_condition_detail_page.scss, hip/static/styles/pages/health_alert_list_page.scss, hip/static/styles/pages/home_page.scss
https://caktus.atlassian.net/browse/HP-141
- adds a fixed `table-layout` to the `tables` mixin
- uses the `tables` mixin on pages with tables throughout the site
=> [HP-141] Fixed Layout For Tables

apps/hip/templates/includes/sidebar.html
https://caktus.atlassian.net/browse/HP-134
Left sidebar links to related websites, conferences, and newsletter now link to those pages' URLs.
=> [HP-148] Update Left Sidebar Links To URLs

apps/hip/templates/hip/home_page.html, hip/static/styles/_mixins.scss, hip/static/styles/pages/health_alert_list_page.scss, hip/static/styles/pages/home_page.scss
https://caktus.atlassian.net/browse/HP-152
=> HP-152 Make border spacing part of table mixin

apps/disease_control/templates/disease_control/disease_and_condition_detail_page.html, apps/disease_control/templates/disease_control/disease_and_condition_list_page.html, apps/disease_control/templates/disease_control/disease_control_list_page.html, apps/emergency_response/templates/emergency_response/emergency_response_page.html, apps/hip/templates/hip/home_page.html, apps/hip/templates/includes/breadcrumb.html, apps/posters/templates/posters/poster_list_page.html, apps/reports/templates/reports/data_report_detail_page.html, hip/static/styles/includes/breadcrumbs.scss, hip/static/styles/pages/disease_and_condition_detail_page.scss, hip/static/styles/pages/disease_control_list_page.scss, hip/static/styles/pages/home_page.scss, hip/static/styles/pages/poster_list_page.scss
https://caktus.atlassian.net/browse/HP-151
This pull request tries to make the space between the left sidebar and the main content of a page consistent across the site, so the breadcrumb element can be consistently spaced, and so that the pages look consistent to each other.
=> [HP-151] Consistent Spacing Between Left Sidebar And Main Content

apps/auth_content/templates/auth_content/big_cities_home_page.html, apps/auth_content/templates/auth_content/closed_pod_child_page.html, apps/auth_content/templates/auth_content/closed_pod_home_page.html, apps/auth_content/templates/auth_content/pcwmsa_home_page.html, hip/static/styles/icons.scss
https://caktus.atlassian.net/browse/HP-155  
This pull request: 
- removes the lock icon from all pages in the repo
- removes the lock icon from the `icons.scss` file
=> [HIP-155] Remove Lock Icon From Authenticated Pages

requirements/base/base.txt, requirements/deploy/deploy.txt, requirements/dev/dev.txt
https://github.com/caktus/philly-hip/security/dependabot
This updates the Python packages that dependabot is complaining about.
=> Update dependencies to satisfy dependabot

apps/hip/static/js/loggedInDropdown.js, apps/hip/templates/includes/header.html, apps/hip/templates/includes/logged_in_dropdown.html, hip/static/js/index.js
https://caktus.atlassian.net/browse/HP-153
This PR:
1) Adds logged-in dropdown based off of this figma wireframe: https://www.figma.com/file/OZAfVKxh8fs8XE7RLnlbY7/PDPH-COVID19?node-id=1697%3A4313
2) Refactors header.html
User should be able to close the dropdown by clicking outside of the dropdown area.
=> HP-153 - Logged In Dropdown

hip/static/styles/pages/static_page.scss
https://caktus.atlassian.net/browse/HP-163
This pull request updates the `StaticPage` styles to include the `wagtail-richtext` mixin for static pages, so that list styling is applied.
=> [HP-163] Show Bullets On StaticPage

apps/emergency_response/templates/includes/partner_login_card.html
https://caktus.atlassian.net/browse/HP-164
This pull request updates the emergency response page card text to match the JIRA ticket.
=> [HP-164] Update Emergency Response Page Card Text

apps/common/models.py
https://caktus.atlassian.net/browse/HP-160
=> [HP-160] Update is_pcwmsa_page method

apps/hip/templates/includes/sidebar.html
https://caktus.atlassian.net/browse/HP-160
- adds a `/` to the end of each of the PCW MSA links in the sidebar
- adds a link for the PIO Contact Information page to the PCW MSA section of the sidebar
=> [HP-160] Sidebar Links

apps/auth_content/forms.py, apps/auth_content/tests/test_forms.py, apps/auth_content/tests/test_views.py, apps/auth_content/views.py
https://caktus.atlassian.net/browse/HP-166
=> HP-166 User can only edit their own info

.github/workflows/deploy.yml, .github/workflows/test.yml, apps/users/signals.py, apps/users/tests/test_signals.py, requirements/base/base.in, requirements/base/base.txt
https://caktus.atlassian.net/browse/DIS-1669
- adds the `django-ipware` library to the project 
- adds Django signals to log for when a user logs in (`log_successful_login`) and logs out (`log_successful_logout`) of the site
=> [DIS-1669] Logging For Login And Logout

apps/auth_content/admin.py, apps/health_alerts/admin.py, apps/users/admin.py, hip/settings/base.py, requirements/base/base.in, requirements/base/base.txt, requirements/dev/dev.txt
https://caktus.atlassian.net/browse/DIS-1687
This PR:
- Adds `django-import-export` package
- Adds the `ExportMixin` to the `Users` and `HealthAlertsSubscribers` adminModel
- Django Admin users are now able to export users and healthalertsubscriber records in a variety of file formats.
=> DIS-1687 - Django-Import-Export 

apps/hip/static/js/rightScrollNav.js, apps/notifications/static/js/notificationSignup.js
**Note: this pull request depends on #204, which should be reviewed first**
This pull request fixes JavaScript console errors by only running code for certain elements if the elements are found on the page.
=> Fix JavaSCript Console Errors

apps/hip/templates/registration/login.html, hip/static/styles/common.scss
https://caktus.atlassian.net/browse/DIS-1716
This pull request adds more specific rules about padding, so that the login button text fits within the button.
=> [DIS-1716] Keep Login Button Text Within Button

deploy/group_vars/all.yml, deploy/requirements.yml
K8s is updated to 1.20
- caktus/philly-hip#218
=> Update cluster and related services

apps/hip/templates/includes/footer.html
https://caktus.atlassian.net/browse/DIS-1774
- updates the "Right to Know" page link text in the footer to be "Right to Know"
- updates the "Right to Know" link in the footer to go to the "/right-to-know/" URL
=> [DIS-1774] Change Footer Link To New Right to Know Page

deploy/host_vars/production.yml
=> Revert "Production Deploy 2021-11-17"

hip/settings/base.py
This deploy to production includes the following work:
#236
=> Production Deploy 2022-03-03

requirements/base/base.txt, requirements/dev/dev.txt
This pull request upgrades Django to the latest bugfix version, [3.2.15](https://www.djangoproject.com/weblog/2022/aug/03/security-releases/)
=> Updates base.txt and dev.txt to Django's latest bugfix

hip/static/styles/common.scss
[Ticket](https://caktus.atlassian.net/browse/DIS-1797)
This PR updates the link color across the whole site, to increase color contrast.
=> [DIS-1797] Updates link color throughout site to improve color contrast

apps/hip/templates/includes/poster_card.html
[Ticket](https://caktus.atlassian.net/browse/DIS-1800?atlOrigin=eyJpIjoiNmUyZTc0ZGE1ZjBjNGQ3NjlmNjUxYTBhYWFmMzg2ODQiLCJwIjoiaiJ9)
This PR:
- Adds alt text to Poster image which provides the title of the image and "English PDF"
- Adds "(PDF)" to end of additional version link text
=> [DIS-1800] Adds alt text to Poster image and (PDF) to the end of the additional language versions

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .dockerignore, .github/workflows/test.yml, .gitignore, .pre-commit-config.yaml, Dockerfile, README.md, docker-compose.yml, docs/hosting-services.md, requirements/dev/dev.in, requirements/dev/dev.txt, tasks.py
- https://app.clickup.com/t/865bb9xvx
Add support for a [Caktus Development Container](https://caktus.github.io/developer-documentation/developer-onboarding/dev-containers/).
=> Add Development Container

Dockerfile, requirements/deploy/deploy.in
Fix `cffi` and `uwsgi` from breaking during deployment.
=> update uwsgi and libffi-dev to build_deps

hip/settings/base.py
To address issues with updating pages with a lot of data.
=> #863fx0b73 Increased the DATA_UPLOAD_MAX_NUMBER_FIELDS

.gitignore, deploy/deploy-cluster.yml, deploy/group_vars/all.yml, docs/hosting-services.md
This has been deployed and is collecting data for the cluster. To see data:
- Login to AWS
- Go to CloudWatch
- Click "All Metrics"
- Click "ContainerInsights"
- Drill down as needed
=> Add aws-cloudwatch-metrics Helm chart

hip/settings/base.py, requirements/base/base.txt, requirements/dev/dev.txt
This pull request upgrades Django to the latest bugfix version for Django3.2.
=> Update To Latest Django Bugfix Version
